### PR TITLE
Add SINGLEFILE_ARGS to control single-file arguments

### PR DESCRIPTION
**Pull request by notevenaperson**
Making a pull request of @renaisun's work for them, since it looks good to me but has been cold for two months.
# Summary

#981 

# Changes these areas

- [ ] Bugfixes
- [ ] Feature behavior
- [ ] Command line interface
- [x] Configuration options
- [ ] Internal architecture
- [ ] Snapshot data layout on disk

### CODE REVIEW

**Comment by renaisun** [comment]
@notevenaperson  Hi, I found this fix is not well rounded. SingleFile need a browser to run which could be set via `--browser-executable-path`. But for archivebox, the browser path is set and passed to singlefile-cli via `CHROME_BINARY`, which seems ambiguous redundant. See [this](https://github.com/ArchiveBox/ArchiveBox/blob/03eb7e58758d8dcb85ed781e713fc083f8292264/archivebox/extractors/singlefile.py#L50)
Should it be removed?

**Comment by notevenaperson** [comment]
> @notevenaperson Hi, I found this fix is not well rounded. SingleFile need a browser to run which could be set via `--browser-executable-path`. But for archivebox, the browser path is set and passed to singlefile-cli via `CHROME_BINARY`, which seems ambiguous redundant. See [this](https://github.com/ArchiveBox/ArchiveBox/blob/03eb7e58758d8dcb85ed781e713fc083f8292264/archivebox/extractors/singlefile.py#L50) Should it be removed?

IMO that's not an issue. For example `COOKIES_FILE` affects wget, but user can still redundantly set `WGET_ARGS=["--load-cookies=cookies.txt"]`. If WGET_ARGS is okay SINGLEFILE_ARGS also is. It's up to the user to sort these redundancies in his or her own config.

**Comment by renaisun** [comment]
> > @notevenaperson Hi, I found this fix is not well rounded. SingleFile need a browser to run which could be set via `--browser-executable-path`. But for archivebox, the browser path is set and passed to singlefile-cli via `CHROME_BINARY`, which seems ambiguous redundant. See [this](https://github.com/ArchiveBox/ArchiveBox/blob/03eb7e58758d8dcb85ed781e713fc083f8292264/archivebox/extractors/singlefile.py#L50) Should it be removed?
> 
> IMO that's not an issue. For example `COOKIES_FILE` affects wget, but user can still redundantly set `WGET_ARGS=["--load-cookies=cookies.txt"]`. If WGET_ARGS is okay SINGLEFILE_ARGS also is. It's up to the user to sort these redundancies in his or her own config.

Sorry for the confusion. I think [there](https://github.com/ArchiveBox/ArchiveBox/blob/03eb7e58758d8dcb85ed781e713fc083f8292264/archivebox/extractors/singlefile.py#L50) shouldn't be `--browser-executable-path` outside the `SINGLEFILE_ARGS`.

Otherwise, the `--browser-executable-path` in SINGLEFILE_ARGS will be overwritten once the user set `CHROME_BINARY`. I'm not sure if there is any guarantee that the arguments are read sequentially.

**Comment by notevenaperson** [comment]
Oh I understand now. If the user sets `SINGLEFILE_ARGS=["--browser-executable-path=foobar"]`, single-file would be given the --browser-executable-path two times. I tested it and it does cause an error:
```
single-file --browser-executable-path=foobar --browser-executable-path=/bin/chromium https://example.com test.html
The "file" argument must be of type string. Received an instance of Array
```
This pull request should also have code to eliminate conflicting (duplicated) options in the final command.

**Comment by notevenaperson** [comment]
I sent a pull request to fix the issue you brought up

[renaisun/ArchiveBox/pull/1](https://github.com/renaisun/ArchiveBox/pull/1)

**Comment by renaisun** [comment]
> @renaisun I sent a pull request to fix the issue. Thanks for bringing it up. If you accept the pull request, it'll be added here.
> 
> [renaisun/ArchiveBox/pull/1](https://github.com/renaisun/ArchiveBox/pull/1)

Thanks for your work. Let's see if the PR will be merged🤣

**Comment by pirate** [comment]
Thanks for your work here! Will review this soon.

**Comment by tzwm** [comment]
@pirate please review this issue. I really want to add more args to singlefile. Thanks!

**Pull request merged**
