### PR TITLE
Add submodules and links

### PR DESCRIPTION
**Pull request by jdcaballerov**
# Summary

Adds vendored code as git submodules with links

# Related issues

#581 
# Changes these areas

- [ ] Bugfixes
- [ ] Feature behavior
- [ ] Command line interface
- [ ] Configuration options
- [x] Internal architecture
- [ ] Snapshot data layout on disk

### CODE REVIEW

**Comment by jdcaballerov** [comment]
I added relative soft links to the python module inside the submodule to avoid touching the imports in the code.

**Comment by pirate** [comment]
Did you run the tests on this? It doesn't appear to be working:
https://github.com/ArchiveBox/ArchiveBox/pull/552/checks?check_run_id=1564480879#step:13:48

**Comment by jdcaballerov** [comment]
@pirate ArchiveBox tests run ok. Pytest is discovering django-taggit owns tests and failing due to a missing test dependency. Will search how to configure pytest to avoid tests inside vendored.

**Comment by jdcaballerov** [comment]
Errors in tests fixed ignoring vendored modules tests https://github.com/ArchiveBox/ArchiveBox/pull/588

**Pull request merged**
