### PR TITLE
fix the URL_REGEX used in generic_html parsers

### PR DESCRIPTION
**Pull request by tqobqbq**
Fix the URL_REGEX in utils.py

I crawled a url:
url="https://twitter.com/share?url=https://akaao.success-corp.co.jp&text=アカイイト＆アオイシロ 公式サイト&hashtags=アカアオ,元祖百合,アカイイト,アオイシロ"
and the re.findall(URL_REGEX, url) in the generic_html.py will return 
['https://twitter.com/share?url=https://akaao.success-corp.co.jp&text=アカイイト＆アオイシロ', 'https://akaao.success-corp.co.jp&text=アカイイト＆アオイシロ'],
the latter is a wrong url which will raise error both in real browser and requests.
image

And In fact, the origin URL_REGEX:
```
URL_REGEX = re.compile(
    r'(?=('
    r'http[s]?://'
    r'(?:[a-zA-Z]|[0-9]'                      # 3
    r'|[-_$@.&+!*\(\),]'                     # 4
    r'|(?:%[0-9a-fA-F][0-9a-fA-F]))'  # 5
    r'[^\]\[\(\)<>"\'\s]+' 
    r'))',
    re.IGNORECASE,
)
```
it's line 3,4,5 will just catch only one char as there is no '+' follow them.
i change it to more standard one:
```
URL_REGEX = re.compile(
    r'(?=('
    r'https?://'                        #match schemes http and https,but can't match ftp
    r'(?:[A-Za-z0-9-]+\.)+[A-Za-z0-9-]+'#match domain
    r'(?::\d+)?'                        #match port,mabey not occur
    r'(?:/[^\\#\f\n\r\t\v]*)?'          #match path and query,maybe not occur
##    r'(?:#[^\]\[\(\)<>"\'\s]*){0,1}'  #match fragment,but don't need it actually 
    r'))',
##    re.IGNORECASE,                    #don't need to consider case problem
)
```
and it works for my example

### CODE REVIEW

**Comment by pirate** [comment]
This is intentional 🙂   I want it to match both because both are syntactically valid URLs regardless of whether they exist in the world or not.

**Comment by tqobqbq** [comment]
@pirate 
I undestand your intention.
My point is that the latter url "https://akaao.success-corp.co.jp&text=アカイイト＆アオイシロ" is syntactically  invalid both in browsers(tested in Chrome and Edge) and python(requests and urllib module).

In browsers,it will not be parsed as a url,just treated as a string and jump to a search engine to search the string.
In requests.get,it will raise requests.exceptions.InvalidURL error


That's because '&' before '?' is illeagal 

I guess you want to extract the redirect url so use the findall.In that case my URL_REGEX can get the correct result:
['https://twitter.com/share?url=https://akaao.success-corp.co.jp&text=アカイイト＆アオイシロ 公式サイト&hashtags=アカアオ,元祖百合,アカイイト,アオイシロ', 'https://akaao.success-corp.co.jp'] 
which may be you want

and after some test,I get a more precise version:
URL_REGEX = re.compile(
    r'(?=('
    r'https?://'                        
    r'(?:[A-Za-z0-9-]+\.)*[A-Za-z0-9-]+'
    r'[^\\#\f\n\r\t\v?&]*'      
    r'(?:\?[^\\#\f\n\r\t\v]*)*'  
    r'))',
)

**Comment by pirate** [comment]
You're right, sorry! I will check some other libraries to make sure it works:

- https://docs.python.org/3/howto/urllib2.html
- https://jmrware.com/articles/2009/uri_regexp/URI_regex.html
- https://www.geeksforgeeks.org/python-check-url-string/

**Comment by tqobqbq** [comment]
Thank you for your reply.
I find a problem in first commit and make some modifications.You can just test the second commit.

**Comment by pirate** [comment]
After further testing I think I like this regex the best. It allows `https://example.com&somearg=before+slash` but it fixes many of the other edge cases.

```python
URL_REGEX = re.compile(
    r'(?=('                           +
    r'http[s]?://'                    +  # start matching from allowed schemes
    r'(?:[a-zA-Z]|[0-9]'              +  # followed by allowed alphanum characters
    r'|[-_$@.&+!*\(\),]'              +  #   or allowed symbols (keep hyphen first to match literal hyphen)
    r'|[^\u0000-\u007F])+'            +  #   or allowed unicode bytes
    r'[^\]\[\(\)<>"\'\s]+'            +  # stop parsing at these symbols
    r'))',
    re.IGNORECASE | re.UNICODE,
)
URL_REGEX_TESTS = [
    ('https://example.com', ['https://example.com']),
    ('http://abc-file234example.com/abc?def=abc&23423=sdfsdf#abc=234&234=a234', ['http://abc-file234example.com/abc?def=abc&23423=sdfsdf#abc=234&234=a234']),

    ('https://twitter.com/share?url=https://akaao.success-corp.co.jp&text=ア@サ!ト&hashtags=ア%オ,元+ア.ア-オ_イ*シ$ロ abc', ['https://twitter.com/share?url=https://akaao.success-corp.co.jp&text=ア@サ!ト&hashtags=ア%オ,元+ア.ア-オ_イ*シ$ロ', 'https://akaao.success-corp.co.jp&text=ア@サ!ト&hashtags=ア%オ,元+ア.ア-オ_イ*シ$ロ']),
    ('<a href="https://twitter.com/share#url=https://akaao.success-corp.co.jp&text=ア@サ!ト?hashtags=ア%オ,元+ア&abc=.ア-オ_イ*シ$ロ"> abc', ['https://twitter.com/share#url=https://akaao.success-corp.co.jp&text=ア@サ!ト?hashtags=ア%オ,元+ア&abc=.ア-オ_イ*シ$ロ', 'https://akaao.success-corp.co.jp&text=ア@サ!ト?hashtags=ア%オ,元+ア&abc=.ア-オ_イ*シ$ロ']),

    ('///a',                                                []),
    ('http://',                                             []),
    ('http://../',                                          ['http://../']),
    ('http://-error-.invalid/',                             ['http://-error-.invalid/']),
    ('http://उदाहरण.परीक्षा',                                  ['http://उदाहरण.परीक्षा']),
    ('http://例子.测试',                                     ['http://例子.测试']),
    ('http://➡.ws/䨹 htps://abc.1243?234',                  ['http://➡.ws/䨹']),
    ('http://⌘.ws">https://exa+mple.com//:abc ',            ['http://⌘.ws', 'https://exa+mple.com//:abc']),
    ('http://مثال.إختبار/abc?def=ت&ب=abc#abc=234',          ['http://مثال.إختبار/abc?def=ت&ب=abc#abc=234']),
    ('http://-.~_!$&()*+,;=:%40:80%2f::::::@example.c\'om', ['http://-.~_!$&']),
    
    ('http://us:pa@ex.co:42/http://ex.co:19/a?_d=4#-a=2.3', ['http://us:pa@ex.co:42/http://ex.co:19/a?_d=4#-a=2.3', 'http://ex.co:19/a?_d=4#-a=2.3']),
    ('http://code.google.com/events/#&product=browser',     ['http://code.google.com/events/#&product=browser']),
    ('http://foo.bar?q=Spaces should be encoded',           ['http://foo.bar?q=Spaces']),
    ('http://foo.com/blah_(wikipedia)#c(i)t[e]-1',          ['http://foo.com/blah_']),
    ('http://foo.com/(something)?after=parens',             ['http://foo.com/']),
    ('http://foo.com/unicode_(✪)_in_parens',                ['http://foo.com/unicode_']),
    ('http://foo.bar/?q=Test%20URL-encoded%20stuff',        ['http://foo.bar/?q=Test%20URL-encoded%20stuff']),
]
for url_str, expected_url_matches in URL_REGEX_TESTS:
    url_matches = re.findall(URL_REGEX, url_str)
    if url_matches != expected_url_matches:
        print('FAILED URL_REGEX CHECK', url_str)
        print('matched: ', url_matches)
        print('expected:', expected_url_matches)
        print()
```

**Pull request merged**
